- name: Set Hostname
  ansible.builtin.shell: set-hostname mongodb

- name: setup mongodb repos
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: setup mongodb repos
  ansible.builtin.template:
    src: mongod.conf
    dest: /etc/mongod.conf

- name: Start mongodb
  ansible.builtin.systemd_service:
    state: restarted
    name: mongod
    enabled: yes

