- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable old nodejs and enable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: Recursively remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: extract catalogue application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      ansible.builtin.command:
        cmd: npm install
      args:
        chdir: /app

    - name: Copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Reload daemon and start catalogue service
      ansible.builtin.systemd:
        daemon_reload: true
        name: catalogue
        state: started
        enabled: yes

    - name: Copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install mongodb client
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present



    - name: load catalogue data
      ansible.builtin.command: mongo --host mongodb.chowdary.cloud < /app/schema/catalogue.js


    - name: start and enable catalogue
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes
