- name: setup catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download and extract content
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /app
        remote_src: yes


    - name: Install NodeJS dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: copy mongodb repo
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service


    - name: demon reload and start
      ansible.builtin.systemd_service:
        daemon_reload: true


    - name: setup mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mangodb-client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: present


    - name: Load Schema
      ansible.builtin.shell: mongo --host mongodb.chowdary.cloud </app/schema/catalogue.js


    - name: start catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started