    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download and extract content
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/user.zip ###
        dest: /app
        remote_src: yes

    - name: Install  dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app


    - name: demon reload and start
      ansible.builtin.shell: npn install


    - name: start user service
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes