- name: Install mongodb component
  hosts: mongodb
  become: yes
  tasks:
    - name: Setup host name
      ansible.builtin.shell:
        cmd: set-hostname mongodb

    - name: setup mongodb repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mangodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present


    - name: start and enable mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: allow remote conncections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: start and enable mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted
        enabled: yes

