- name: Install mongodb component
  hosts: mongodb
  become: yes
  tasks:
    - name: Setup host name
      ansible.builtin.shell:
        cmd: set-hostname mongodb

    - name: setup mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mangodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present


    - name: Update MongoDB Listen address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'


    - name: Start and enable mongodb
      ansible.builtin.service:
        name: mongodb
        state: restarted
        enabled: yes

