- name: install mysql component
  hosts: mysql
  become: yes
  tasks:
    - name: disable current version of mysql
      ansible.builtin.command: dnf module disable mysql -y

    - name: setup mysql5.7 repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Add MySQL repository
      ansible.builtin.yum_repository:
        name: mysql57-community
        description: MySQL 5.7 Community Server
        baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el7/$basearch/
        gpgcheck: yes
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        enabled: yes


    - name: start and enable mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

