- name: Install mysql component
  hosts: mysql
  become: yes
  tasks:
    - name: disable MySQL 8 version
      ansible.builtin.shell: dnf module disable mysql -y

    - name: copy mysql repo
      ansible.builtin.copy:
        src: mysql.rpo
        dest: /etc/yum.repos.d/mysql.repo

    - name: install mysql server
      ansible.builtin.package:
        name: mysql-community-server
        state: present

    - name: start and enable mysql
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes
    - name: setup mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
