- name: Setup MySQL server
  hosts: mysql
  become: yes
  tasks:
    - name: Add MySQL repository
      ansible.builtin.yum_repository:
        name: mysql57-community
        description: MySQL 5.7 Community Server
        baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el7/$basearch/
        gpgcheck: yes
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        enabled: yes

    - name: Clean yum cache
      ansible.builtin.command:
        cmd: yum clean all

    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-community-server
        state: present
        enabled: yes
