- name: Install nginx
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: Removing Old Web Content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Downloading Nginx Web Content & Extract it
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /tmp
        remote_src: yes


    - name: copy roboshop configuration
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf


    - name: start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes

