- name: Set Hostname
  ansible.builtin.shell: set-hostname frontend

- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Cleanup old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download backend Code and Extract it
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Placing Expense Config File in Nginx     # Reverse Proxy Configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: yes

- name: Install Filebeat
  ansible.builtin.import_role:
    name: common
    tasks_from: public-IP




#  ---------------


#- name: Update Nginx Config  # log setup
#  ansible.builtin.template:
#    src: nginx.conf
#    dest: /etc/nginx/nginx.conf

#- name: Include App Pre-requisites
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: app_prereq